export const RecordingAudioTypes = {
    // RECORDING TYPES
    UPDATE_RECORDING_LIST: "UPDATE_RECORDING_LIST ",
    SET_SOUND: "SET_SOUND",
    SET_SOUND_PAUSE: "SET_SOUND_PAUSE",
    SET_SOUND_STOPPED: "SET_SOUND_STOPPED",
    SET_CURRENT_SOUND_PLAYING: "SET_CURRENT_SOUND_PLAYING",
    SET_CURRENT_SOUND_RECORDING: "SET_CURRENT_SOUND_RECORDING",
    SET_CURRENT_PLAYING_STATUS: "SET_CURRENT_PLAYING_STATUS",
    SET_DURATION_MILLIS: "SET_DURATION_MILLIS",
    SET_SLIDING_POSITION: "SET_SLIDING_POSITION",
    SET_RECORDING: "SET_RECORDING",
    SET_IS_RECORDING: "SET_IS_RECORDING",
    SET_RECORD_URI: "SET_RECORD_URI",
    SET_RECORDING_DURATION: "SET_RECORDING_DURATION",

}

